spring:
  application:
    name: Car-Migo
  datasource:
    username: admin
    password: password
    url: jdbc:postgresql://localhost:5432/carmigo
  jpa:
    database-platform: carmigo
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
        temp:
          use_jdbc_metadata_defaults: false
  cache:
    redis:
      time-to-live: 10800000  # 3 hours
  data:
    redis:
      repositories:
        enabled: false
  cloud:
    discovery:
      client:
        composite-indicator:
          enabled: false

server:
  port: 8086

logging:
  level:
    web: INFO

application:
  token:
    secret:
      key: Q2FyLW1pZ28gYXBwbGljYXRpb24gaXMgYXdlc29tZSEgSXQgd2lsbCByZXZvbHV0aW9uaXplIHRoZSB3YXkgeW91IGdldCBhcm91bmQuIEl0IGlzIGVjby1mcmllbmRseSBhbmQgaGVscHMgeW91ciBwb2NrZXQuIFRoZSBhcHBsaWNhdGlvbiBpcyBxdWl0ZSBzdHJhaWdodHdheSwgeW91IGNhbiBlaXRoZXIgYWR2ZXJ0aXNlIHJpZGVzIG9yIHF1ZXJ5IHRoZW0uIFdoZW4gaW5zaWRlIHRoZSBjYXIgc2hhcmUsIHlvdSBjYW4gZW5qb3kgdGhlIHJpZGUgYW5kIG1ha2UgbmV3IGZyaWVuZHMuIENvbWUgb25ib2FyZCBhbmQgZXhwZXJpZW5jZSB0aGlzIG5ldyBsaWZlc3R5bGUu
    expiration:
      in-hours: 10

open-feign:
  distance:
    endpoint: https://distanceto.p.rapidapi.com/get
    host: distanceto.p.rapidapi.com
    key: ${CAR_MIGO_OPEN_FEIGN_DISTANCE_KEY:unknown_open_feign_distance_key}

springdoc:
  api:
    description: RESTful API for CRUD operations on users (platform users, drivers and passengers) and journeys.
    title: ${spring.application.name} API
  show-actuator: true
  swagger-ui:
    displayOperationId: true
    tagsSorter: alpha
  use-fqn: true
  writer-with-order-by-keys: true

management:
  endpoints:
    web:
      exposure:
        include: "beans, health, info, metrics"
  endpoint:
    health:
      show-details: always
  health:
    mail:
      enabled: false

redis:
  hostname: localhost
  port: 6379
  connection_timeout: 5000
  command_timeout: 5000

---
spring:
  config:
    activate:
      on-profile: dev

debug: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/carmigo
  devtools:
    add-properties: false

redis:
  hostname: redis
