# For further information about Maven workflows
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# For further information about CodeQL workflows
# Language support: https://git.io/codeql-language-support
# Queries: ./path/to/local/query, your-org/your-repo/queries@main
# Command-line programs to run using the OS shell:https://git.io/JvXDl

name: Car-Migo builds with Maven and Node.js, CodeQL and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
#   runs every first day of the month at 7:00am
    - cron: '0 7 1 * *'

env:
# this is used by /journeys/calculateDistance endpoint
  CAR_MIGO_OPEN_FEIGN_DISTANCE_KEY: ${{ secrets.CAR_MIGO_OPEN_FEIGN_DISTANCE_KEY }}

jobs:
  maven:
    name: Maven Build
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: cd ./server && ./mvnw clean verify && cd ..

  node:
    name: Node Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build with Node
        run: cd ./ui && npm ci && npm run lint && cd ..

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ['java']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  docker:
    name: Docker
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: cd ./server && ./mvnw clean verify -DskipTests && cd ..
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - run: docker build -t car-migo_server --target server .
      - run: docker tag car-migo_server ${{ secrets.DOCKER_HUB_USERNAME }}/car-migo_server:latest
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/car-migo_server:latest
      - run: docker build -t car-migo_ui --target ui .
      - run: docker tag car-migo_ui ${{ secrets.DOCKER_HUB_USERNAME }}/car-migo_ui:latest
      - run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/car-migo_ui:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
