# For further information about Maven workflows
# https://docs.docker.com/ci-cd/github-actions/

name: Docker build and push

on:
  push:
    branches:
      - "updates"
jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./../../
          file: ./../../Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/carmigo:latest
